// SPDX-License-Identifier: MIT
//
// The sprite sheet and its manifest, compiled into the binary.
//
// Loading happens up front rather than lazily: the manifest is a build artefact
// baked into the executable, so a failure here is a packaging bug that must be
// reported loudly, not swallowed at the first frame.

use serde_json::Value;
use skia_rs::codec::Image;

/// Generated by build.rs from tools/gen_sprites.py.
const SHEET_DEFAULT: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/spritesheet.png"));
const SHEET_FANCY: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/spritesheet-fancy.png"));
const SHEET_PARTY: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/spritesheet-party.png"));
const MANIFEST_JSON: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/manifest.json"));

#[derive(Debug, Clone, PartialEq)]
pub struct Animation {
    pub name: String,
    pub row: i32,
    pub frames: usize,
    pub fps: f64,
    pub looping: bool,
}

#[derive(Debug, Clone, PartialEq)]
pub struct Manifest {
    pub frame_width: i32,
    pub frame_height: i32,
    pub animations: Vec<Animation>,
}

impl Manifest {
    /// Parse the compiled-in manifest.
    pub fn embedded() -> Result<Self, String> {
        Self::parse(MANIFEST_JSON)
    }

    pub fn parse(raw: &[u8]) -> Result<Self, String> {
        let root: Value =
            serde_json::from_slice(raw).map_err(|e| format!("manifest is not valid JSON: {e}"))?;
        let obj = root.as_object().ok_or("manifest is not a JSON object")?;

        let frame_width = obj.get("frameWidth").and_then(Value::as_i64).unwrap_or(64) as i32;
        let frame_height = obj.get("frameHeight").and_then(Value::as_i64).unwrap_or(64) as i32;
        if frame_width <= 0 || frame_height <= 0 {
            return Err(format!("manifest frame size is {frame_width}x{frame_height}"));
        }

        let list = obj
            .get("animations")
            .and_then(Value::as_array)
            .ok_or("manifest has no animations array")?;

        let mut animations = Vec::with_capacity(list.len());
        for entry in list {
            let e = entry.as_object().ok_or("animation entry is not an object")?;
            let name = e
                .get("name")
                .and_then(Value::as_str)
                .ok_or("animation entry has no name")?
                .to_string();
            let frames = e.get("frames").and_then(Value::as_i64).unwrap_or(1).max(1) as usize;
            let fps = e.get("fps").and_then(Value::as_f64).unwrap_or(8.0);
            animations.push(Animation {
                name,
                row: e.get("row").and_then(Value::as_i64).unwrap_or(0) as i32,
                frames,
                // A zero or negative fps would divide by zero in the frame
                // clock; the manifest is generated, but it is still input.
                fps: if fps > 0.0 { fps } else { 8.0 },
                looping: e.get("loop").and_then(Value::as_bool).unwrap_or(true),
            });
        }
        if animations.is_empty() {
            return Err("manifest lists no animations".to_string());
        }

        Ok(Self { frame_width, frame_height, animations })
    }

    pub fn get(&self, name: &str) -> Option<&Animation> {
        self.animations.iter().find(|a| a.name == name)
    }

    pub fn names(&self) -> Vec<&str> {
        self.animations.iter().map(|a| a.name.as_str()).collect()
    }
}

/// Decode the sheet for a sprite variant.
pub fn load_sheet(variant: &str) -> Result<Image, String> {
    let raw = match variant {
        "fancy" => SHEET_FANCY,
        "party" => SHEET_PARTY,
        // config::load has already rejected unknown variants; this is the
        // belt-and-braces path.
        _ => SHEET_DEFAULT,
    };
    skia_rs::codec::decode_image(raw).map_err(|e| format!("cannot decode {variant} sheet: {e:?}"))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn embedded_manifest_parses() {
        let m = Manifest::embedded().expect("embedded manifest must parse");
        assert_eq!(m.frame_width, 64);
        assert_eq!(m.frame_height, 64);
        // Every animation the brain can ask for has to exist.
        for required in
            ["sleep", "walk", "scuttle", "creep", "think", "wave", "celebrate", "tumble"]
        {
            assert!(m.get(required).is_some(), "manifest is missing {required}");
        }
    }

    #[test]
    fn one_shots_are_not_looping() {
        let m = Manifest::embedded().unwrap();
        // The brain relies on these ending so it can clear the reaction.
        assert!(!m.get("celebrate").unwrap().looping);
        assert!(!m.get("tumble").unwrap().looping);
        assert!(m.get("walk").unwrap().looping);
    }

    #[test]
    fn every_variant_decodes() {
        for variant in crate::config::SPRITE_VARIANTS {
            let img = load_sheet(variant).unwrap_or_else(|e| panic!("{variant}: {e}"));
            assert_eq!(img.width(), 640);
            assert_eq!(img.height(), 512);
        }
    }

    #[test]
    fn sheet_is_tall_enough_for_every_row() {
        let m = Manifest::embedded().unwrap();
        let img = load_sheet("default").unwrap();
        for a in &m.animations {
            let bottom = (a.row + 1) * m.frame_height;
            assert!(bottom <= img.height(), "{} row {} runs off the sheet", a.name, a.row);
            let right = a.frames as i32 * m.frame_width;
            assert!(right <= img.width(), "{} has {} frames, too wide", a.name, a.frames);
        }
    }

    #[test]
    fn rejects_a_broken_manifest() {
        assert!(Manifest::parse(b"not json").is_err());
        assert!(Manifest::parse(br#"{"frameWidth":64}"#).is_err());
        assert!(Manifest::parse(br#"{"animations":[]}"#).is_err());
    }

    #[test]
    fn zero_fps_falls_back_rather_than_dividing_by_zero() {
        let m = Manifest::parse(
            br#"{"frameWidth":64,"frameHeight":64,
                 "animations":[{"name":"x","row":0,"frames":2,"fps":0,"loop":true}]}"#,
        )
        .unwrap();
        assert!(m.get("x").unwrap().fps > 0.0);
    }
}
